config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root 'users#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users do
	  resources :artists
	  resources :albums
	  resources :songs
	end

  resources :favorites

end

app/models/artist.rb
class Artist < ApplicationRecord
	belongs_to :user
	has_many   :albums
	has_many   :songs, through: :albums
	has_many   :favorites, as: :favoriteable

	def self.search(search)
		if search
			self.where('name LIKE ?', "%#{search}%")
		else
			self.all
		end
	end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    find_artist_favorites
    @artists = Artist.search(params[:search])
  end

  def show
    find_album_favorites
    @albums = @artist.albums
    @album = Album.new
  end

  def new
    @artist = Artist.new
  end

  def edit
  end

  def create
    @artist = Artist.new(user_id: params[:user_id], name: params[:artist][:name] )

    respond_to do |format|
      if @artist.save
        format.html { redirect_to user_artists_url(current_user), notice: 'Artist was successfully created.' }
        format.js   {}
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @artist.update(user_id: params[:user_id], name: params[:artist][:name] )
        format.html { redirect_to user_artist_path(current_user, @artist), notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to user_artists_url(current_user), notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private
    def find_artist_favorites
      @favorites = Favorite.where(user_id: current_user.id, favoriteable_type: "Artist")
    end

    def find_album_favorites
      @favorites = Favorite.where(user_id: current_user.id, favoriteable_type: "Album")
    end

    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.fetch(:artist, {})
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_artist.html.erb
<tr>
  <td><%= link_to @artist.name, user_artist_path(current_user, @artist) %></td>
  <td><%= link_to 'Edit', edit_user_artist_path(current_user, @artist) %></td>
  <td><%= link_to 'Destroy', user_artist_path(current_user, @artist), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: 'delete-artist' %></td>
  <td><%= render partial: "layouts/favorite", locals: {user: current_user, media: @artist} %></td>
</tr>

app/views/artists/_form.html.erb
<%= form_for [user, artist], html: {class: 'create-artist'}, remote: true do |f| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="actions">
    <%= f.text_field :name %>
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/create.js.erb
$("<%= escape_javascript(render @artist) %>").appendTo('.artists-list');

app/views/artists/destroy.js.erb
$('.delete-artist').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render partial: 'form', locals: {user: current_user, artist: @artist} %>

<%= link_to 'Show', user_artist_path(current_user, @artist) %> |
<%= link_to 'Back', user_artists_path(current_user) %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Artists</h1>
<%= form_tag user_artists_path(current_user), :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Artist</th>
    </tr>
  </thead>

  <tbody class='artists-list'>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= link_to artist.name, user_artist_path(current_user, artist) %></td>
        <td><%= link_to 'Edit', edit_user_artist_path(current_user, artist) %></td>
        <td><%= link_to 'Destroy', user_artist_path(current_user, artist), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: 'delete-artist' %></td>
        <td><%= render partial: "layouts/favorite", locals: {user: current_user, media: artist} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render partial: 'form', locals: {user: current_user, artist: Artist.new}, remote: true, class: 'create-artist' %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render partial: 'form', locals: {user: current_user, artist: @artist } %>

<%= link_to 'Back', user_artists_path(current_user, @artist) %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @artist.name %></h1>
<h3>Albums:</h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>

<tbody>
  <% @albums.each do |album| %>
    <tr>
      <td><%= link_to album.title, user_album_path(current_user, album) %></td>
      <td><%= link_to 'Edit', edit_user_album_path(current_user, album, artist: @artist) %></td>
      <td><%= link_to 'Destroy', user_album_path(current_user, album), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= render partial: "layouts/favorite", locals: {user: current_user, media: album} %></td>
    </tr>
  <% end %>
</tbody>

</table>
<br>
<%= link_to 'New Album', new_user_album_path(current_user, artist: @artist) %>

<br>
<br>

<%= link_to 'Edit', edit_user_artist_path(current_user, @artist) %> |
<%= link_to 'Back', user_artists_path(current_user) %>