config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root 'users#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users do
	  resources :artists
	  resources :albums
	  resources :songs
	end

  resources :favorites

end

app/models/album.rb
class Album < ApplicationRecord
	belongs_to :user
	belongs_to :artist
	has_many   :songs
	has_many   :favorites, as: :favoriteable

	def self.search(search)
		if search
			self.where('title LIKE ?', "%#{search}%")
		else
			self.all
		end
	end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    find_album_favorites
    @albums = Album.search(params[:search])
  end

  def show
    @songs = @album.songs
  end

  def new
    @album = Album.new
    @artist = Artist.find(params[:artist])
  end

  def edit
    @artist = Artist.find(params[:artist])
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @album = Album.new(user_id: params[:user_id], artist_id: params[:artist_id], title: params[:album][:title])

    respond_to do |format|
      if @album.save
        format.html { redirect_to user_album_path(current_user, @album), notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @album.update(user_id: params[:user_id], artist_id: params[:artist_id], title: params[:album][:title])
        format.html { redirect_to user_album_path(current_user, @album), notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to user_albums_url(current_user), notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def find_album_favorites
      @favorites = Favorite.where(user_id: current_user.id, favoriteable_type: "Album")
    end

    def find_song_favorites
      @favorites = Favorite.where(user_id: current_user.id, favoriteable_type: "Song")
    end

    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.fetch(:album, {})
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for [user, album] do |f| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <p>Title:</p>
    <%= f.text_field :title %>
    <%= hidden_field_tag :artist_id, artist.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render partial: 'form', locals: {user: current_user, album: @album, artist: @artist} %>

<%= link_to 'Show', user_album_path(current_user, @album) %> |
<%= link_to 'Back', user_albums_path(current_user) %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<%= form_tag user_albums_path(current_user), :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :title => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Album</th>
    </tr>
  </thead>

  <tbody>
  <% @albums.each do |album| %>
    <tr>
      <td><%= link_to album.artist.name, user_artist_path(current_user, album.artist) %></td>
      <td><%= link_to album.title, user_album_path(current_user, album) %></td>
      <td><%= link_to 'Edit', edit_user_album_path(current_user, album) %></td>
      <td><%= link_to 'Destroy', user_album_path(current_user, album), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= render partial: "layouts/favorite", locals: {user: current_user, media: album} %></td>

    </tr>
  <% end %>
</tbody>

</table>

<br>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render partial: 'form', locals: {user: current_user, album: @album, artist: @artist }%>

<%= link_to 'Back', user_albums_path(current_user) %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @album.title %></h1>
<h3>by: <%= link_to @album.artist.name, user_artist_path(current_user, @album.artist) %></h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= link_to song.title, user_song_path(current_user, song) %></td>
        <td><%= link_to 'Edit', edit_user_song_path(current_user, song, album: @album) %></td>
        <td><%= link_to 'Destroy', user_song_path(current_user, song), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= render partial: "layouts/favorite", locals: {user: current_user, media: song} %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br> 
<%= link_to 'New Song', new_user_song_path(current_user, album: @album) %>
<br>
<br>

<%= link_to 'Edit', edit_user_album_path(current_user, @album, artist: @album.artist) %> |
<%= link_to 'Back', user_albums_path(current_user) %>