config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root 'users#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users do
	  resources :artists
	  resources :albums
	  resources :songs
	end

  resources :favorites

end

app/views/layouts/_favorite.html.erb
<% if media.favorites.where(user_id: user).empty? %>
	<%= button_to "Add to Favorites", favorites_path(media_id: media.id, media_type: media.class.name), class: 'create-favorites', method: :create  %>
<% else %>
	<%= button_to "Remove from Favorites", favorite_path(media.favorites.where(user_id: user).first), class: "delete-favorites", method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recordly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if current_user %>
      <ul>
        <li><%= link_to "Favorites", user_path(current_user) %></li>
  			<li><%= link_to "Artists", user_artists_path(current_user) %></li>
  			<li><%= link_to "Albums", user_albums_path(current_user) %></li>
  			<li><%= link_to "Songs", user_songs_path(current_user) %></li>
        <li><%= render 'devise/menu/registration_items' %></li>
        <li><%= render 'devise/menu/login_items' %></li>
      </ul>
  	<% end %>
    <%= yield %>
  </body>
</html>